oplus_chg-objs := gauge_ic/oplus_bq27541.o \
	vooc_ic/oplus_n76e.o \
	vooc_ic/oplus_vooc_fw.o \
	vooc_ic/oplus_stm8s.o \
	vooc_ic/oplus_rk826.o \
	vooc_ic/oplus_op10.o \
	adapter_ic/oplus_stm.o \
	charger_ic/oplus_short_ic.o \
	oplus_charger.o \
	oplus_gauge.o \
	oplus_vooc.o \
	oplus_adapter.o \
	oplus_wireless.o \
	oplus_short.o \
	oplus_debug_info.o \
	oplus_configfs.o
obj-$(CONFIG_OPLUS_CHG) += oplus_chg.o
obj-$(CONFIG_OPLUS_BQ25601D_SLAVE_CHARGER)	+= charger_ic/oplus_bq25600_slave.o
